### PR TITLE
Adding the `xsv lua`command

### PR DESCRIPTION
**Pull request by Yomguithereal**
Hello @BurntSushi,

A PR based upon & revamping @Dimagog lua PR #136, adding a `xsv lua` command which is able either to `map` or `filter` a CSV file by executing a Lua script over the iterated lines.

This makes complex filtering (such as comparison on number values and such) a possibility.

I could add a `reduce` option but I don't personally need it right now.

I switched from `rlua` to `hlua` because I need performance more than safety in my use cases, this should be stated so that people don't expose the tool to external users (but I guess that's not the point of the tool anyway).

I think it will be my last PR for now. Sorry for the notifications avalanche. I maintain a little fork of the tool for my lab on a branch [here](https://github.com/Yomguithereal/xsv/tree/prod#how-to-install) if you ever need it.

Have a good day,

### CODE REVIEW

**Comment by BurntSushi** [comment]
@Yomguithereal thanks! But yeah, I think Lua for something like this isn't a good fit for this tool.

> Sorry for the notifications avalanche.

Aye. And I'm going to close your PRs as well, since every time you push a change to one of those branches, I get pinged again.

**Comment by Yomguithereal** [comment]
No problem @BurntSushi. I am also all too familiar with notification exhaustion. Take care.

**Comment by BurntSushi** [comment]
@Yomguithereal Aye. After looking at your PRs, some of them look quite useful. I'm going to try to work on xsv again, overhauling some things, and I will try to incorporate your ideas. I don't think I'll accept them as-is since I'd like to take a more holistic view of things, but your use cases sound great!

**Comment by Yomguithereal** [comment]
Ok @BurntSushi. Feel free to contact me if you need anything or if you want more details about my typical use cases. For now I will stop opening new PRs on the repo to avoid needless notifications (I think I have added most of what I need for now anyway). Let me just state once again that your tool has been very valuable to me and my coworkers. Thank you very much for your work.

**Pull request closed without merging**
