### PR TITLE
Added another installation method

### PR DESCRIPTION
**Pull request by mehandes**
Added NIx/NixOS installation method

### CODE REVIEW

**Comment by BurntSushi** [comment]
@mehandes Thanks! But did you send a PR to the wrong repo? It looks like this is for ripgrep, not xsv. :-)

**Comment by mehandes** [comment]
@BurntSushi fixed ;)

**Comment by michelboaventura** [comment]
I think the text is still wrong. It says:

If you're a **Nix/NixOS** user, you can install RIPGREP from nixpkgs

**Comment by BurntSushi** [comment]
@michelboaventura Thanks for the heads up. I fixed it.

**Pull request merged**
